services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    platform: linux/arm64
    ports:
      - "8545:8545"
    command: ["-a 3", "-e 100"]
  agents:
    build: .
    depends_on:
      - ganache 
    